# -*- coding: utf-8 -*-
"""Final Project_Kelompok 13_Visualisasi Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C8SW-ysVTVAsrHUsIvSLAuraxyFf-z1A

#Library & import data
"""

from bokeh.io import output_notebook, curdoc
from bokeh.plotting import figure, show
from bokeh.models.widgets import Tabs, Panel
from bokeh.models import ColumnDataSource, GroupFilter, CDSView, HoverTool, Div
from bokeh.layouts import column, widgetbox
import pandas as pd
import numpy as np


df_stock = pd.read_csv("SahamMNCBank.csv", parse_dates = ["Date"])
df_stock = df_stock.rename(columns={"Ratio(%)" : 'Ratio'})
df_stock['Index']= df_stock.index + 1
df_stock.head()

"""#Sortir data """

#sort data
source = ColumnDataSource(df_stock)
source_mnc = CDSView(source=source)

#set circle info
circle_data = {'source': source, 'size': 3, 'alpha': 0.7, 'selection_color':'black'}

circle_mnc = {'view': source_mnc, 'color': 'red', 'legend_label': 'MNC Bank'}

"""#Figure Close"""

#create figur
output_notebook()
select_tools = ['pan', 'box_select', 'wheel_zoom', 'tap', 'reset']
fig1 = figure(title= 'Close Data',x_axis_type='datetime',x_axis_label='Date', y_axis_label= 'Close',
              plot_height=500, plot_width=800, toolbar_location="right",tools=select_tools)

#add data circle
fig1.circle(x='Date', y='Close', **circle_data, **circle_mnc)

#add Hover
tooltips= [('Name','MNC Bank'),('Close', '@Close') ]
hover_glyph = fig1.circle(x='Date', y= 'Close' , source=source,size=3, alpha=0, hover_fill_color='black', hover_alpha=0.5)
fig1.add_tools(HoverTool(tooltips=tooltips, renderers=[hover_glyph]))

#hide data via legend(Level 3)
fig1.legend.click_policy = 'hide'
fig1.legend.location= 'top_right'

"""#Figure Volume"""

#create figur
output_notebook()
select_tools = ['pan', 'box_select', 'wheel_zoom', 'tap', 'reset']
fig2 = figure(title= 'Volume Data',x_axis_type='datetime',x_axis_label='Date', y_axis_label= 'Volume',
              plot_height=500, plot_width=800, toolbar_location="right",tools=select_tools)

#add data circle
fig2.circle(x='Date', y='Volume', **circle_data, **circle_mnc)

#add Hover
tooltips= [('Name','MNC Bank'),('Volume', '@Volume') ]
hover_glyph = fig2.circle(x='Date', y= 'Volume' , source=source,size=3, alpha=0,hover_fill_color='black', hover_alpha=0.5)
fig2.add_tools(HoverTool(tooltips=tooltips, renderers=[hover_glyph]))

#hide data via legend(Level 3)
fig2.legend.click_policy = 'hide'
fig2.legend.location= 'top_right'

"""#Figure Ratio
Change Price time of the day (using percentage rupiah)
"""

#create figur
output_notebook()
select_tools = ['pan', 'box_select', 'wheel_zoom', 'tap', 'reset']
fig3 = figure(title= 'Ratio Data',x_axis_type='datetime',x_axis_label='Date', y_axis_label= 'Ratio',
              plot_height=500, plot_width=800, toolbar_location="right",tools=select_tools)

#add data circle
fig3.circle(x='Date', y='Ratio', **circle_data, **circle_mnc)

#add Hover
tooltips= [('Name','MNC Bank'),('Ratio', '@Ratio %') ]
hover_glyph = fig3.circle(x='Date', y= 'Ratio' , source=source,size=3, alpha=0,hover_fill_color='black', hover_alpha=0.5)
fig3.add_tools(HoverTool(tooltips=tooltips, renderers=[hover_glyph]))

#hide data via legend(Level 3)
fig3.legend.click_policy = 'hide'
fig2.legend.location= 'top_right'

"""#Configure Panel"""

# Output to file
output_file('Visualisasi Saham MNC.html', title='Visualisasi Saham MNC')

#add title
isi = """<h1>Fluktuasi Harga Saham MNC Bank 2014 - 2021</h1>
<h3><i>Click Legend to HIDE Data</i><h3>"""
title = Div(text=isi)
#add widget panel and tab
fig1_panel = Panel(child=fig1, title='Close Data')
fig2_panel = Panel(child=fig2, title='Volume Data')
fig3_panel = Panel(child=fig3, title='Ratio Data (%)')
tab = Tabs(tabs=[fig1_panel, fig2_panel, fig3_panel])
#add layout
show(column(title,tab))